### ISSUE TITLE
P1/P2 Assignments Swapped on Neo Geo Core with MVS (or AES) BIOS Loaded

### ISSUE THREAD

**Issue by charles-spurgeon** [misteraddons/MiSTercade-Config#1]
MiSTercade is connected in a Capcom Big Blue Cabinet with default JAMMA/CPS2 wiring and when Neo•Geo games are loaded using either AES or MVS BIOS, player assignments are swapped.  The player assignments are as expected in CPS2 games and other arcade cores, including SNK arcade cores, but not Neo•Geo.  JAMMA/NG wiring schematic for P1/P2 appears to be the same.  Restart/Reboot and reconfiguring buttons doesn't help.

**Comment by misteraddons** [comment]
I don't see how that's possible based on how the main MiSTer binary handles controls. I just checked on my cabinet and it behaved properly. Test: load NeoGeo core using only the P2 controls. Load Samurai Showdown 2. Insert 2 credits and press P2 start. P2 controls P2 and P1 controls P1 without ever touching P1 controls. See if you can replicate that :)
